services:
  jjigit-app:
    image: jjigit-backend:latest
    container_name: jjigit-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PROD_DB_HOST=${PROD_DB_HOST}
      - PROD_DB_PORT=${PROD_DB_PORT}
      - PROD_DB_NAME=${PROD_DB_NAME}
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - PROD_SERVER_URL=${PROD_SERVER_URL}
    restart: unless-stopped

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: jjigit_db
    ports:
      - "3306:3306"
    container_name: mysql-jjigit
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
