services:

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: asd1234
      MYSQL_DATABASE: jjigit_db
    ports:
      - "3306:3306"
    container_name: mysql-jjigit
    volumes:
      - ./mysql_data:/var/lib/mysql
